FORMAT: 1A
HOST: http://tinkerware.io

# Engine API
Engine is a service to manage the projects a user owns.

# Group Projects
Project management

## Project Collection [/api/v1/project]

### Add a new Project [POST]
+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "project": {
                    "user_id": 1,
                    "project_name": "tinkerware",
                    "application_name": "simple_webpage",
                    "server_provider": "digital_ocean",
                    "configuration": {
                        "a": "a",
                        "b": "b"
                    },
                    "repository": {
                        "provider": "github",
                        "name": "ghost-blog"
                    }
                }
            }

+ Response 201 (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "project": {
                    "id": "507f1f77bcf86cd799439011",
                    "user_id": 1,
                    "project_name": "tinkerware",
                    "application_name": "simple_webpage",
                    "server_provider": "digital_ocean",
                    "configuration": {
                        "a": "a",
                        "b": "b"
                    },
                    "repository": {
                        "provider": "github",
                        "name": "ghost-blog"
                    }
                }
            }

### Get a list of an user Projects [GET]
+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

+ Response 200 (application/json)
    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf
    + Body

            {
                "projects": [
                    {
                        "id": "507f1f77bcf86cd799439011",
                        "user_id": 1,
                        "project_name": "tinkerware",
                        "application_name": "simple_webpage",
                        "server_provider": "digital_ocean",
                        "configuration": {
                            "a": "a",
                            "b": "b"
                        },
                        "repository": {
                            "provider": "github",
                            "name": "ghost-blog"
                        }
                    }
                ]
            }

## Project Collection [/api/v1/project/{id}]
+ Parameters
    + id (required, string, `507f1f77bcf86cd799439011`) ... `id` of the project

### Get a single Project [GET]
+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

+ Response 200 (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "project": {
                    "id": "507f1f77bcf86cd799439011",
                    "user_id": 1,
                    "project_name": "tinkerware",
                    "application_name": "simple_webpage",
                    "server_provider": "digital_ocean",
                    "configuration": {
                        "a": "a",
                        "b": "b"
                    },
                    "repository": {
                        "provider": "github",
                        "name": "ghost-blog"
                    }
                }
            }

### Modify an existing Project [PUT]
+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "project": {
                    "id": "507f1f77bcf86cd799439011",
                    "user_id": 1,
                    "project_name": "tinkerware.web",
                    "application_name": "simple_webpage",
                    "server_provider": "digital_ocean",
                    "configuration": {
                        "a": "a",
                        "b": "b"
                    },
                    "repository": {
                        "provider": "github",
                        "name": "ghost-blog"
                    }
                }
            }

+ Response 200 (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "project": {
                    "id": "507f1f77bcf86cd799439011",
                    "user_id": 1,
                    "project_name": "tinkerware.web",
                    "application_name": "simple_webpage",
                    "server_provider": "digital_ocean",
                    "configuration": {
                        "a": "a",
                        "b": "b"
                    },
                    "repository": {
                        "provider": "github",
                        "name": "ghost-blog"
                    }
                }
            }

### Delete a Project [DELETE]

+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

+ Response 204

# Group Deploy
Project management

## Deploy Collection [/api/v1/project/{projectid}/deploys]

+ Parameters
    + projectid (required, string, `507f1f77bcf86cd799439011`) ... `projectid` of the project

### Add a new Deploy [POST]
+ Request (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "deploy": {
                    "user_id": 1,
                    "project_id": "507f1f77bcf86cd799439011",
                    "note": "nightly build",
                    "status": "Pending",
                    "commit": "fc5e502cfc908db401394337548131cc739e777f"
                }
            }

+ Response 201 (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "deploy": {
                    "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                    "user_id": 1,
                    "project_id": "507f1f77bcf86cd799439011",
                    "deployed_at": "2014-04-17T14:00:00.030Z",
                    "note": "nightly build",
                    "commit": "fc5e502cfc908db401394337548131cc739e777f",
                    "status": "Pending"
                }
            }

### Get a list of a projects deploys [GET]
+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

+ Response 200 (application/json)
    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf
    + Body

            {
                "deploys": [
                    {
                        "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                        "user_id": 1,
                        "project_id": "507f1f77bcf86cd799439011"
                        "deployed_at": "2014-04-17T14:00:00.030Z",
                        "note": "nightly build",
                        "commit": "fc5e502cfc908db401394337548131cc739e777f",
                        "status": "Pending"
                    }
                ]
            }

## Deploy Collection [/api/v1/project/{projectid}/deploys/{id}]
+ Parameters
    + id (required, string, `a3hk4lf2g0n1vxny5mninv8fsqwzqf`) ... `id` of the deploy
    + projectid (required, string, `507f1f77bcf86cd799439011`) ... `projectid` of the project

### Get a single Deploy [GET]
+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

+ Response 200 (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "deploy": {
                    "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                    "user_id": 1,
                    "project_id": "507f1f77bcf86cd799439011"
                    "deployed_at": "2014-04-17T14:00:00.030Z",
                    "note": "nightly build",
                    "commit": "fc5e502cfc908db401394337548131cc739e777f",
                    "status": "Pending"
                }
            }

### Modify an existing Deploy [PUT]
+ Request (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "deploy": {
                    "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                    "user_id": 1,
                    "project_id": "507f1f77bcf86cd799439011",
                    "deployed_at": "2014-04-17T14:00:00.030Z",
                    "note": "nightly build",
                    "commit": "fc5e502cfc908db401394337548131cc739e777f",
                    "status": "In Progress"
                }
            }

+ Response 200 (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "deploy": {
                    "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                    "user_id": 1,
                    "project_id": "507f1f77bcf86cd799439011",
                    "deployed_at": "2014-04-17T14:00:00.030Z",
                    "note": "nightly build",
                    "commit": "fc5e502cfc908db401394337548131cc739e777f",
                    "status": "In Progress"
                }
            }

### Delete a Server [DELETE]

+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

+ Response 204

# Group Server
Server management

## Server Collection [/api/v1/project/{projectid}/servers]
+ Parameters
    + projectid (required, string, `507f1f77bcf86cd799439011`) ... `projectid` of the project

### Add a new Server [POST]
+ Request (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "server": {
                    "deploy_id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                    "project_id": "507f1f77bcf86cd799439011",
                    "instance_id": "1",
                    "operating_system": "debian-8-x64",
                    "instance_name": "521mb",
                    "region": "nyc1",
                    "hostname": "tinkerware.com",
                    "status": "Created",
                    "provider": "digital_ocean",
                    "networks": {
                        "v4": [
                          {
                            "ip_address": "104.131.186.241",
                            "netmask": "255.255.240.0",
                            "gateway": "104.131.176.1",
                            "type": "public"
                          }
                        ],
                        "v6": [
                          {
                            "ip_address": "2604:A880:0800:0010:0000:0000:031D:2001",
                            "netmask": 64,
                            "gateway": "2604:A880:0800:0010:0000:0000:0000:0001",
                            "type": "public"
                          }
                        ]
                      }
                }
            }

+ Response 201 (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "server": {
                    "id": "5xOQluuygRCrGFn7QcT1zDiS",
                    "deploy_id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                    "project_id": "507f1f77bcf86cd799439011",
                    "ip": "192.168.1.1",
                    "operating_system": "debian-8-x64",
                    "instance_name": "521mb",
                    "region": "nyc1",
                    "hostname": "tinkerware.com",
                    "status": "created",
                    "provider": "digital_ocean"
                }
            }

### Get a list of a projects servers [GET]
+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

+ Response 200 (application/json)
    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf
    + Body

            {
                "servers": [
                    {
                        "id": "5xOQluuygRCrGFn7QcT1zDiS",
                        "deploy_id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                        "project_id": "507f1f77bcf86cd799439011",
                        "ip": "192.168.1.1",
                        "operating_system": "debian-8-x64",
                        "instance_name": "521mb",
                        "region": "nyc1",
                        "hostname": "tinkerware.com",
                        "status": "not created",
                        "provider": "digital_ocean"
                    }
                ]
            }

## Server Collection [/api/v1/project/{projectid}/servers/{id}]
+ Parameters
    + id (required, string, `507f1f77bcf86cd799439011`) ... `id` of the Server
    + projectid (required, string, `507f1f77bcf86cd799439011`) ... `projectid` of the project

### Get a single Server [GET]
+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

+ Response 200 (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "server": {
                    "id": "5xOQluuygRCrGFn7QcT1zDiS",
                    "deploy_id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                    "project_id": "507f1f77bcf86cd799439011",
                    "ip": "192.168.1.1",
                    "operating_system": "debian-8-x64",
                    "instance_name": "521mb",
                    "region": "nyc1",
                    "hostname": "tinkerware.com",
                    "status": "not created",
                    "provider": "digital_ocean"
                }
            }

### Modify an existing Project [PUT]
+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "server": {
                    "id": "5xOQluuygRCrGFn7QcT1zDiS",
                    "deploy_id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                    "project_id": "507f1f77bcf86cd799439011",
                    "ip": "192.168.1.1",
                    "operating_system": "debian-8-x64",
                    "instance_name": "521mb",
                    "region": "nyc1",
                    "hostname": "tinkerware.com",
                    "status": "building",
                    "provider": "digital_ocean"
                }
            }


+ Response 200 (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "server": {
                    "id": "5xOQluuygRCrGFn7QcT1zDiS",
                    "deploy_id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                    "project_id": "507f1f77bcf86cd799439011",
                    "ip": "192.168.1.1",
                    "operating_system": "debian-8-x64",
                    "instance_name": "521mb",
                    "region": "nyc1",
                    "hostname": "tinkerware.com",
                    "status": "building",
                    "provider": "digital_ocean"
                }
            }

### Delete a Deploy [DELETE]

+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

+ Response 204

# Group Development Environment
Development files management

## Development Environment Collection [/api/v1/project/{projectid}/dev_environment]

+ Parameters
    + projectid (required, string, `507f1f77bcf86cd799439011`) ... `projectid` of the project

### Add a new Development Environment [POST]
+ Request (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
              "development_environment":
              {
                "project_id":"507f1f77bcf86cd799439011",
                "path":"https://s3-us-west-1.amazonaws.com/tw-test123/asdfgh.zip"
              }
            }

+ Response 201 (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "development_environment": {
                    "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                    "project_id": "507f1f77bcf86cd799439011",
                    "path": "https://s3-us-west-1.amazonaws.com/tw-test123/asdfgh.zip"
                }
            }

### Get a list of a projects development environments [GET]
+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

+ Response 200 (application/json)
    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf
    + Body

            {
                "development_environments": [
                  {
                    "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                    "path": "https://s3-us-west-1.amazonaws.com/tw-test123/asdfgh.zip"
                  },
                  {
                    "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqg",
                    "path": "/path/to/file/b.zip"
                  },
                  {
                    "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqg",
                    "path": "/path/to/file/c.zip"
                  },
                  {
                    "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqi",
                    "path": "/path/to/file/d.zip"
                  }
                ]
            }

## Development Environment Collection [/api/v1/project/{projectid}/dev_environment/{id}]
+ Parameters
    + id (required, string, `a3hk4lf2g0n1vxny5mninv8fsqwzqf`) ... `id` of the development environment
    + projectid (required, string, `507f1f77bcf86cd799439011`) ... `projectid` of the project

### Get a single Deploy [GET]
+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

+ Response 200 (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "development_environment": {
                  "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                  "path": "https://s3-us-west-1.amazonaws.com/tw-test123/asdfgh.zip"
                }
            }

### Modify an existing development environment [PUT]
+ Request (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "development_environment": {
                  "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                  "path": "https://s3-us-west-1.amazonaws.com/tw-test123/asdfgh.zip"
                }
            }

+ Response 200 (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
                "deploy": {
                  "id": "a3hk4lf2g0n1vxny5mninv8fsqwzqf",
                  "path": "https://s3-us-west-1.amazonaws.com/tw-test123/asdfgh.zip"
                }
            }

### Delete a Deploy [DELETE]

+ Request

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

+ Response 204
