FORMAT: 1A
HOST: http://api.tinkerware.io

# Provision API
An API that when a deploy is provisioned.

# Group Provision
Provision management

## Users Collection [/api/v1/provision]
### Register an user [POST]
+ Request (application/json)

    + Header

            authorization: Bearer qphYSqjEFk1RcFxYqqIIFk4vaBJvDoBr3t9aHTp1JFEAO0NS7ECyLJJyUPybOUNf

    + Body

            {
              "user_id": 99999,
              "ssh_keys": [{
              "title": "some content",
              "key": "some_content",
              "fingerprint": null
              }],
              "server_provider": "digital_ocean",
              "repository": {
                "provider": "github",
                "name": "user/reponame"
              },
              "project_name": "tinkerware.web",
              "id": "57cf8fe8ce40ef0bbf803d66",
              "configuration": {
                "b": "b",
                "a": "a"
              },
              "application_name": "codeigniter"
            }

+ Response 202
